config/routes.rb
Rails.application.routes.draw do

  root 'public/homes#show'

  devise_for :admins, controllers: {
    sessions:       'admins/sessions',
    passwords:      'admins/passwords',
    registrations:  'admins/registrations'
  }

  devise_for :customers, controllers: {
    sessions:       'customers/sessions',
    passwords:      'customers/passwords',
    registrations:  'customers/registrations'
  }

  namespace :admin do
    get "/"=>"homes#top"
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
  end
  
  namespace :public do
    get "/about"=>"homes#about"
    resources :items, only: [:index, :show]
    resources :orders, only: [:new, :index, :show, :create]
    get "/orders/success"=>"orders#success"
    post "/orders/confirm"=>"orders#confirm"
    patch "/customers/withdraw" =>"customers#withdraw"
    get "/customers/result" => "customers#result"
    resources :customers, only:[:show, :edit, :update]
    resources :cart_items, only: [:index, :create, :update, :destroy]
    delete "/cart_items/destroy_all" => "cart_items#destroy_all"
    resources :shipping_adresses, only: [:index, :edit, :create, :update, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,:registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def active_for_authentication?
    super && (self.is_deleted == false)
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
 belongs_to :genre
 has_one_attached :image

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def after_tax_on_price
     tax_off_price * 1.10
  end
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
end

app/models/shipping_adress.rb
class ShippingAdress < ApplicationRecord
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to request.referrer
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
    @genre = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genre = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  private
  def item_params
    params.require(:item).permit(:genre_id, :image, :name, :introduction, :tax_off_price, :selling_status)
  end


end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
  end
end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :first_name_kana, :last_name_kana, :email, :post_code, :adress, :tel_number])
  end
end

app/helpers/admin/cart_items_helper.rb
module Admin::CartItemsHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row">

    <div class="col">
      <h1>ジャンル編集</h1>
      <%= form_with model: @genre, url: admin_genre_path, method: :patch do |f| %>
        <%= f.label :name, "ジャンル名" %>
        <%= f.text_field :name, placeholder: "genre.name" %>
        <%= f.submit "変更を保存" %>
      <% end%>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row">

    <div class="col">
      <h1>ジャンル一覧・追加</h1>
      <%= form_with model: @genre, url: admin_genres_path do |f| %>
        <%= f.label :name, "ジャンル名" %>
        <%= f.text_field :name, placeholder: "新規ジャンル名", rows: 10 %>
        <%= f.submit "新規登録" %>
      <% end %>
    </div>

    <div class="col">
      <h2>ジャンル</h2>
      <% @genres.each do |genre| %>
        <p><%= genre.name %></p>
        <%= link_to "編集する", edit_admin_genre_path(genre.id) %>
      <% end %>
    </div>

  </div>
</div>

app/views/admin/items/edit.html.erb
<h1>商品編集画面</h1>

<%= form_with model: @item, url: admin_item_path(@item.id), method: :patch do |f| %>
  <table>
    <tr>
      <td><%= f.label :image, "商品画像"%></td>
      <td><%= f.file_field :image, accept: "/image*" %></td>
    </tr>
    <tr>
      <td><%= f.label :name ,"商品名" %></td>
      <td><%= f.text_field :name, placeholder: "商品名" %></td>
    </tr>
    <tr>
      <td><%= f.label :introduction, "商品説明" %></td>
      <td><%= f.text_area :introduction, placeholder: "@item.introduction"  %></td>
    </tr>
    <tr>
      <td><%= f.label :genre_id, "ジャンル名"%></td>
      <td><%= f.collection_select(:genre_id, @genre, :id, :name, prompt: "選択してください")%></td>
    </tr>
    <tr>
      <td><%= f.label :tax_off_price, "税抜き価格" %></td>
      <td><p><%= f.text_field :tax_off_price, placeholder: "1000" %>円</p></td>
    </tr>
    <tr>
      <td><%=f.label :selling_status, "販売ステータス" %></td>
      <td>
        <%= f.radio_button :selling_status, :true, checked: true %>
        <%= f.label :selling_status, "販売中" %>
      </td>
      <td>
        <%= f.radio_button :selling_status, :false %>
        <%= f.label :selling_status, "売切れ" %>
      </td>
    </tr>
    <tr>
      <td><%= f.submit '編集を保存' %></td>
    </tr>
  </table>
<% end %>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">

    <div class="col">
      <h1>商品一覧</h1>
    </div>
    <div class="col">
      <%= link_to "新規商品登録", new_admin_item_path %>
    </div>

    <div class="col">
      <table>
        <thead>
          <tr>
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜価格</th>
            <th>ジャンル</th>
            <th>販売ステータス</th>
          </tr>
        </thead>
        <tr>
          <% @items.each do |item| %>
            <td><%= item.id %></td>
            <td><%= link_to item.name, admin_item_path(item) %></td>
            <td><%= item.tax_off_price %></td>
            <td><%= item.genre.name%></td>
            <% if item.selling_status == true %>
              <td>販売中</td>
            <% else %>
              <td>売切れ</td>
            <% end %>
          <% end %>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<h1>商品新規登録</h1>

<%= form_with model: @item, url: admin_items_path do |f| %>
  <table>
    <tr>
      <td><%= f.label :image, "商品画像"%></td>
      <td><%= f.file_field :image, accept: "/image*" %></td>
    </tr>
    <tr>
      <td><%= f.label :name ,"商品名" %></td>
      <td><%= f.text_field :name, placeholder: "商品名" %></td>
    </tr>
    <tr>
      <td><%= f.label :introduction, "商品説明" %></td>
      <td><%= f.text_area :introduction, placeholder: "ここに説明文を記入します"  %></td>
    </tr>
    <tr>
      <td><%= f.label :genre_id, "ジャンル名"%></td>
      <td><%= f.collection_select(:genre_id, @genre, :id, :name, prompt: "選択してください")%></td>
    </tr>
    <tr>
      <td><%= f.label :tax_off_price, "税抜き価格" %></td>
      <td><p><%= f.text_field :tax_off_price, placeholder: "1000" %>円</p></td>
    </tr>
    <tr>
      <td><%=f.label :selling_status, "販売ステータス" %></td>
      <td>
        <%= f.radio_button :selling_status, :true, checked: true %>
        <%= f.label :selling_status, "販売中" %>
      </td>
      <td>
        <%= f.radio_button :selling_status, :false %>
        <%= f.label :selling_status, "売切れ" %>
      </td>
    </tr>
    <tr>
      <td><%= f.submit '新規投稿' %></td>
    </tr>
　</table>
<% end %>

app/views/admin/items/show.html.erb
<table>
  <thead>
    <th><p>商品詳細</p></th>
  </thead>
  <tbody>
    <tr>
      <td><%= image_tag @item.get_image(300,300) %></td>
    </tr>
    <tr>
      <td><p>商品名</p></td>
      <td><%= @item.name %></td>
    </tr>
    <tr>
      <td><p>商品説明</p></td>
      <td><%= @item.introduction %></td>
    </tr>
    <tr>
      <td><p>ジャンル</p></td>
      <td><%= @item.genre.name %></td>
    </tr>
    <tr>
      <td>税込価格（税抜価格）</td>
      <td><%= @item.after_tax_on_price.round %>(<%= @item.tax_off_price %>)円</td>
    </tr>
    <tr>
      <td><p>販売ステータス</p></td>
      <td>
        <% if @item.selling_status == true %>
          <p>販売中</p>
        <% else %>
          <p>売切れ</p>
        <% end %>
      </td>
    </tr>
    <tr>
      <td>
        <%= link_to "編集する", edit_admin_item_path(@item) %>
      </td>
    </tr>
  </tbody>
</table>

app/views/admin/orders/show.html.erb
<h1>Admin::Orders#show</h1>
<p>Find me in app/views/admin/orders/show.html.erb</p>